server:
  port: 8080

spring:
  application:
    name: arena-booking
  profiles:
    active: dev
  
  # Disable JPA since we're using Firebase
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

firebase:
  project-id: asiatiger-d8136
  service-account-key: serviceAccountKey.json

logging:
  level:
    com.university.arenabooking: DEBUG
    org.springframework.security: DEBUG
    
cors:
  allowed-origins: http://localhost:3000